export const globalActions = {
  INIT: "INIT",
  POPUP_INIT: "POPUP_INIT",
  SET_OPTIONS: "SET_OPTIONS",
  LINK_TO_POPUP: "GET_SELECTED_TEXT",
  ON_POPUP_CLOSE: "ON_POPUP_CLOSE",
  ADD_TO_HISTORY: "ADD_TO_HISTORY",
  TOGGLE_HISTORY_REVIEW: "TOGGLE_HISTORY_REVIEW",
  REMOVE_HISTORY_ITEM: "REMOVE_HISTORY_ITEM",
  CLEAR_HISTORY: "CLEAR_HISTORY",
  GET_PUBLIC_API_USAGE: "GET_PUBLIC_API_USAGE",
  COUNT_UP_PUBLIC_API_USAGE: "COUNT_UP_PUBLIC_API_USAGE",
  COUNT_UP_REVIEW_LINK_CLICK: "COUNT_UP_REVIEW_LINK_CLICK",
}

export const publicApiDetails = {
  key: "6b3a80cc-9d9f-4007-9ee5-52a24ab7eb31",
  type: "sd3",
  usageLimitPerInstall: 20
}

export const defaultOptions = {
  apiKey: publicApiDetails.key,
  apiType: publicApiDetails.type,
  wordSelectMode: "",
  pauseVideoOnPopupOpen: true,
  isRelativeHistoryPromoted: false,
  reviewMode: null,
}

export const API_TYPES = {
  "Dictionary": "collegiate",
  "Thesaurus": "thesaurus",
  "Intermediate Thesaurus": "ithesaurus",
  "Spanish": "spanish",
  "medical_v2": "medical",
  "Elementary Dictionary": "sd2",
  "Intermediate Dictionary": "sd3",
  "School Dictionary": "sd4",
  "Learner's": "learners",
}

export const searchIcon = `<svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 48 48" enable-background="new 0 0 48 48" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><g fill="#616161"><rect x="34.6" y="28.1" transform="matrix(.707 -.707 .707 .707 -15.154 36.586)" width="4" height="17"></rect><circle cx="20" cy="20" r="16"></circle></g><rect x="36.2" y="32.1" transform="matrix(.707 -.707 .707 .707 -15.839 38.239)" fill="#37474F" width="4" height="12.3"></rect><circle fill="#64B5F6" cx="20" cy="20" r="13"></circle><path fill="#BBDEFB" d="M26.9,14.2c-1.7-2-4.2-3.2-6.9-3.2s-5.2,1.2-6.9,3.2c-0.4,0.4-0.3,1.1,0.1,1.4c0.4,0.4,1.1,0.3,1.4-0.1 C16,13.9,17.9,13,20,13s4,0.9,5.4,2.5c0.2,0.2,0.5,0.4,0.8,0.4c0.2,0,0.5-0.1,0.6-0.2C27.2,15.3,27.2,14.6,26.9,14.2z"></path></svg>`;

export const PAGES = {
  Search: "search",
  Result: "Result",
  Options: "Options",
  History: "History",
}

export const ERRORS = {
  EMPTY_SEARCH: "Looking up for nothing!",
  PERSONAL_KEY_NEEDED: "You've reached the limit of using public options. You need to add you FREE personal API key to continue using this extension.\n" +
    "Read the instructions on the Options page to get more info, please!",
  INVALID_API_KEY: "Invalid API options. \n" +
    "Make sure your API key is valid and the API type you choose is the same as the one you chose when you registered.",
  FAILED_TO_FETCH: "It seems you are offline!",
  NO_RESULT: "No result!",
}

export const REVIEW_US = [
  "🤔 To review or not to review?",
  "🌊 Life's a beach - review us!",
  "🤯 What's the meaning? Review us!",
  "🔮 The future looks bright... review us!",
  "🐔 The chicken crossed... to review us!",
  "🌲 If a tree falls... review us!",
  "🕰️ Time flies... so review us!",
  "🤷‍ Who knows what's next? Review us!",
  "💭 Pondering life? Review us instead!",
  "🤔 What's it all for? Reviews!",
  "🌈 The rainbow is a sign... review us!",
  "🌞 The sun is shining... review us!",
  "✈️ Fly high with a five-star review!",
  "🛩️ Buckle up for a wild review!",
  "🦸‍ The captain requests a review!",
  "🌤️ The sky's the limit for reviews!",
  "🚁 Review us for a helicopter view!",
  "🪂 Parachute into a great review!",
  "🛬 Touchdown with a fantastic review!",
  "🛫 Take off to a stellar review!",
  "🛸 Review us for a close encounter!",
  "🦸‍ Be a hero and review us!",
  "👽 We come in peace. Review us!",
  "🕺 Dance the review away with us!",
  "🥳 Celebrate with us and review!",
  "🚀 Blast off to an epic review!",
  "🌪️ A tornado of reviews, please!",
  "🤪 Our product's weird. Review it anyway!",
  "🦜 We're tweeting for a review!",
  "🤯 Your review could blow our minds!",
  "🥴 We need your review to sober up!",
  "👽 From another planet? Review us!",
  "🕺 If this makes you dance... review!",
  "🧑‍🚀 Review us for an out-of-this-world experience!",
  "🦜 We're squawking for a review!",
  "✨ We believe in magic reviews!",
  "🕺 Dance like nobody's reviewing - but please do!",
  "🦸‍ Save the day with a review!",
  "🐰 Hop to it and review us!",
  "🤪 We're a little bit crazy - review us anyway!",
  "🤖 I'm not a robot, but please review me!",
  "🐶 We're wagging our tails for your review!",
  "👨‍🚀 Blast off to a great review!",
  "🌵 Don't desert us - leave a review!",
  "🌟 Your review = our happiness!",
  "🤗 Share your feedback, please?",
  "📝 Leave a review, pretty please?",
  "🤩 Your opinion matters! Review now.",
  "🚀 Help us soar with a review!",
  "🙏 We'd love your feedback!",
  "🎉 Celebrate with us - review today!",
  "💡 Illuminate us with your review!",
  "🥰 Love it? Hate it? Review!",
  "🤘 Wanna be our hero? Review us!",
  "💪 Help us improve - review now!",
  "🤔 Love it? Hate it? Tell us!",
  "🚀 Let's soar together - review please!",
  "🙌 Give us a high five with a review!",
  "🍻 Your review = free virtual cheers!",
  "💬 Spill the beans - review us!",
  "🎁 Give us the gift of a review!",
  "🤙 Hang loose and review us!",
  "🎤 Your review = our mic drop moment!",
  "🤑 Help us make bank with a review!",
  "🍕 Review us and we'll send virtual pizza!",
  "🦄 Your review = magic to our ears!",
  "🌈 Rainbow unicorns love reviews. Do you?",
  "🤗 Give us a virtual hug - review now!",
  "🙊 Your review = our dirty little secret!",
  "🤫 We won't tell anyone if you review us!",
  "🤖 Beep boop beep! Review us please!",
  "🍺 Review us and we'll send virtual beers!",
  "🙋‍ Help us out - leave review!",
  "💬 Tell us what you think, please!",
  "🌟 We need your feedback, friend!",
  "😃 Happy thoughts = happy review!",
  "🤗 We'd love your opinion!",
  "📝 Leave us a review, pretty please!",
  "🥰 We heart reviews - please share!",
  "🌞 Sunny day + review = perfection!",
  "🙌 High five for a great review!",
  "🍩 Your review = virtual donuts!",
  "🥳 Review us and let's party!",
  "🧐 We're curious - review, please!",
  "🍿 Grab some popcorn and review us!",
  "🌟 Let your voice be heard!",
  "💬 Share your thoughts with us!",
  "👀 See the power of your review!",
  "🤩 Reviewing is caring!",
  "🌟 Let's make a difference with your review!",
  "🙏 Help us improve with your review!",
  "🎉 Celebrate with us - leave a review!",
  "🤔 Your thoughts count! Review us!",
  "🤘 Wanna be our hero? Review now!",
  "😎 Your review will rock our world!",
]
